// <auto-generated />
using ChangeManager.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChangeManager.Infra.Data.Migrations
{
    [DbContext(typeof(ChangeManagerContext))]
    [Migration("20191221185054_CoinCorrection")]
    partial class CoinCorrection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChangeManager.Domain.Entities.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("Value")
                        .HasColumnName("value")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("coin");
                });

            modelBuilder.Entity("ChangeManager.Domain.Entities.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("register");
                });

            modelBuilder.Entity("ChangeManager.Domain.Entities.RegisterCoin", b =>
                {
                    b.Property<int>("RegisterId")
                        .HasColumnType("int");

                    b.Property<int>("CoinId")
                        .HasColumnType("int");

                    b.Property<uint>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("int unsigned");

                    b.HasKey("RegisterId", "CoinId");

                    b.HasIndex("CoinId");

                    b.ToTable("RegisterCoin");
                });

            modelBuilder.Entity("ChangeManager.Domain.Entities.RegisterCoin", b =>
                {
                    b.HasOne("ChangeManager.Domain.Entities.Coin", "Coin")
                        .WithMany("RegisterCoins")
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeManager.Domain.Entities.Register", "Register")
                        .WithMany("RegisterCoins")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
